### ISSUE TITLE
[EnchantmentSolution] File write error: enchantment_solution.db

### ISSUE THREAD

**Issue by DiabeticAnna** [crashtheparty/EnchantmentSolution#1]
[16:47:18 ERROR]: [EnchantmentSolution] File write error: enchantment_solution.db
[16:47:18 ERROR]: [EnchantmentSolution] SQLite exception on initialize
java.sql.SQLException: path to 'plugins\EnchantmentSolution\enchantment_solution.db': 'C:\Users\pinea\Documents\Minecraft Server\plugins\EnchantmentSolution' does not exist
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:215) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.sqlite.JDBC.createConnection(JDBC.java:116) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_191]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_191]
        at org.ctp.enchantmentsolution.database.SQLite.getSQLConnection(SQLite.java:98) [EnchantmentSolution(1).jar:?]
        at org.ctp.enchantmentsolution.database.SQLite.load(SQLite.java:113) [EnchantmentSolution(1).jar:?]
        at org.ctp.enchantmentsolution.EnchantmentSolution.onEnable(EnchantmentSolution.java:77) [EnchantmentSolution(1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[16:47:18 ERROR]: Error occurred while enabling EnchantmentSolution v1.3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at org.ctp.enchantmentsolution.database.tables.Table.createTable(Table.java:266) ~[?:?]
        at org.ctp.enchantmentsolution.database.SQLite.load(SQLite.java:115) ~[?:?]
        at org.ctp.enchantmentsolution.EnchantmentSolution.onEnable(EnchantmentSolution.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-573cdf2-1b982fd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by crashtheparty** [comment]
This has been fixed in 1.3.2.
