### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by Tradie18** [crashtheparty/EnchantmentSolution#52]
[WARNING] [EnchantmentSolution] Task #191 for EnchantmentSolution v2.1.14 generated an exception

java.lang.NullPointerException: null

at org.ctp.enchantmentsolution.utils.AuctionHouseUtils.resetAuctionHouse(AuctionHouseUtils.java:26) ~[?:?]

at org.ctp.enchantmentsolution.EnchantmentSolution$1.run(EnchantmentSolution.java:181) ~[?:?]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by crashtheparty** [comment]
It appears to be an item that is not null but doesn't have any item meta was in an Auction House, or that AuctionHouse wasn't enabled (though that shouldn't be the case). This was fixed in 2.2.0.
