### ISSUE TITLE
EnchantmentSolution conflicting with SlimeFun4

### ISSUE THREAD

**Issue by dfsek** [crashtheparty/EnchantmentSolution#56]
I recently installed SlimeFun on my server, and now the console is filling with this error:
```
[19:24:17 ERROR]: Could not pass event InventoryOpenEvent to EnchantmentSolution v2.2.3
java.lang.NumberFormatException: For input string: "a "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at org.ctp.enchantmentsolution.utils.ChatUtils.hexToASCII(ChatUtils.java:164) ~[?:?]
        at org.ctp.enchantmentsolution.utils.ChatUtils.revealText(ChatUtils.java:149) ~[?:?]
        at org.ctp.enchantmentsolution.utils.StringUtils.isEnchantment(StringUtils.java:112) ~[?:?]
        at org.ctp.enchantmentsolution.utils.items.ItemUtils.setLore(ItemUtils.java:126) ~[?:?]
        at org.ctp.enchantmentsolution.utils.items.ItemUtils.removeEnchantmentFromItem(ItemUtils.java:194) ~[?:?]
        at org.ctp.enchantmentsolution.listeners.VanishListener.removeEnchants(VanishListener.java:108) ~[?:?]
        at org.ctp.enchantmentsolution.listeners.VanishListener.onInventoryOpen(VanishListener.java:60) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor394.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-77]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1200) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1186) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:499) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:374) ~[patched_1.15.2.jar:git-Paper-77]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.open(ChestMenu.java:266) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.core.guide.ChestSlimefunGuide.openCategory(ChestSlimefunGuide.java:274) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.core.guide.ISlimefunGuide.handleHistory(ISlimefunGuide.java:45) ~[?:?]
        at me.mrCookieSlime.Slimefun.SlimefunGuide.openGuide(SlimefunGuide.java:112) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.onRightClick(SlimefunItemListener.java:88) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor555.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-77]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-77]
        at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor224.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-77]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373) ~[?:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-77]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Everything appears to be working fine, as no players have reported strange behavior

**Comment by crashtheparty** [comment]
This should've been fixed in 2.2.4
