### ISSUE TITLE
Could not pass PlayerFishEvent

### ISSUE THREAD

**Issue by aulodian** [crashtheparty/EnchantmentSolution#80]
Occurs every time a player fishes and fills the console.
May be related to #72 
```
[14:55:51 ERROR]: Could not pass event PlayerFishEvent to EnchantmentSolution v2.2.15
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
at org.ctp.enchantmentsolution.utils.GenerateUtils.getEnchantments(GenerateUtils.java:95) ~[?:?]
at org.ctp.enchantmentsolution.utils.GenerateUtils.generateFishingLoot(GenerateUtils.java:56) ~[?:?]
at org.ctp.enchantmentsolution.listeners.fishing.EnchantsFishingListener.handleFishing(EnchantsFishingListener.java:29) ~[?:?]
at org.ctp.enchantmentsolution.listeners.fishing.EnchantsFishingListener.onPlayerFishMonitor(EnchantsFishingListener.java:20) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor434.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-228]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-228]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-228]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.EntityFishingHook.b(EntityFishingHook.java:389) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.ItemFishingRod.a(ItemFishingRod.java:36) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.ItemStack.a(ItemStack.java:335) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1453) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[server.jar:git-Paper-228]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[server.jar:git-Paper-228]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by crashtheparty** [comment]
Please report the bug using the following format.

**Describe the bug**
A clear and concise description of what the bug is.

**Debug.yml**
Please send the debug.yml file generated using /esdebug to the bug report. You may use the file uploader on GitHub or a service like [pastebin](https://www.pastebin.com) and send the URL in this area. *Any issues that do not have the debug.yml information will be marked as closed immediately*.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
